### ISSUE TITLE
Where can I find the database?

### ISSUE THREAD

**Issue by JonathanAbrahams1337** [dcouvin/SpolLineages#1]
Hi,

Thank you for making this tool. It is working well for me.

I am trying to understand what database is used by the tool and where this file is in the repo. Could you point me in the right direction?

Is the tool using the SITVIT2 database?

Jonathan

**Comment by dcouvin** [comment]
Hi Jonathan,
Thank you for your message.
Yes SITVIT2 is used by the tool. A spoligo list file (with unique spoligotypes from SITVIT2) has just been added to the repository.
Further details regarding SITVIT2 can be found in the following link: https://doi.org/10.1016/j.meegid.2018.12.030
Hope this will help!
Best,
David

**Comment by JonathanAbrahams1337** [comment]
Hi David, 

That's fantastic, thank you. 

Jonathan
